DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(300),
    DETAIL_ADDRESS VARCHAR2(300),
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,
    
    CONSTRAINT CK_MEMBER_DELETED
        CHECK (IS_DELETED IN ('Y', 'N'))
);

COMMIT;

SELECT * FROM MEMBER;

CREATE TABLE MEMBER_WITHDRAW (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MEMBER_ID VARCHAR2(50),
    REASON VARCHAR2(500),
    REGDATE DATE DEFAULT SYSDATE
);

SELECT * FROM MEMBER_WITHDRAW;

UPDATE MEMBER
SET ROLE = 'ADMIN'
WHERE MEMBER_ID = 'admin01';

SELECT MEMBER_ID, ROLE
FROM MEMBER
WHERE MEMBER_ID = 'admin01';

DROP TABLE board;
CREATE TABLE board (
                       NO			  NUMBER		CONSTRAINT board_no_pk PRIMARY KEY,
                       member_no	  NUMBER		CONSTRAINT board_member_nn NOT NULL,
                       board_type	  VARCHAR2(20)  CONSTRAINT board_type_nn NOT NULL,
                       restaurant_no NUMBER,
                       title		  VARCHAR2(300) CONSTRAINT board_title_nn NOT NULL,
                       content		  CLOB			CONSTRAINT board_content_nn NOT NULL,
                       rating		  NUMBER(2,1),
                       hit			  NUMBER		DEFAULT 0,
                       like_count	  NUMBER		DEFAULT 0,
                       regdate		  DATE			DEFAULT sysdate,
                       update_date	  DATE,
                       IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,
						CONSTRAINT CK_BOARD_DELETED
    						CHECK (IS_DELETED IN ('Y', 'N')),

                       CONSTRAINT board_member_fk
                           FOREIGN KEY (member_no) REFERENCES member(NO),

                       CONSTRAINT board_type_ck
                           CHECK (board_type IN ('FREE', 'REVIEW')),

                       CONSTRAINT board_rating_ck
                           CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);
DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE board_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    nocache
    nocycle;

SELECT * FROM board;
ALTER TABLE board ADD category VARCHAR2(20);
ALTER TABLE board ADD taste_rating number(2,1);
ALTER TABLE board ADD facility_rating number(2,1);
ALTER TABLE board ADD service_rating number(2,1);

ALTER TABLE board ADD CONSTRAINT board_taste_ck
    CHECK (taste_rating IS NULL OR taste_rating BETWEEN 1 AND 5);
ALTER TABLE board ADD CONSTRAINT board_facility_ck
    CHECK (facility_rating IS NULL OR facility_rating BETWEEN 1 AND 5);
ALTER TABLE board ADD CONSTRAINT board_service_ck
    CHECK (service_rating IS NULL OR service_rating BETWEEN 1 AND 5);

COMMIT;
INSERT INTO board (
    NO,
    member_no,
    board_type,
    title,
    content
) VALUES (
             board_seq.nextval,
             3,
             'FREE',
             '자유게시판 테스트 제목',
             '자유게시판 테스트 내용'
         );

SELECT * FROM board;

CREATE TABLE board_comment (
                               NO			NUMBER			CONSTRAINT board_comment_no_pk PRIMARY KEY,
                               board_no	NUMBER			CONSTRAINT board_comment_board_nn NOT NULL,
                               member_no	NUMBER			CONSTRAINT board_comment_member_nn NOT NULL,
                               content		VARCHAR2(1000)	CONSTRAINT board_comment_content_nn NOT NULL,
                               regdate		DATE 			DEFAULT sysdate,
                               update_date	DATE,
                               IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

								CONSTRAINT CK_BOARD_COMMENT_DELETED
    								CHECK (IS_DELETED IN ('Y', 'N')),

                               CONSTRAINT board_comment_board_fk
                                   FOREIGN KEY (board_no) REFERENCES board(NO)
                                       ON DELETE CASCADE ,

                               CONSTRAINT board_comment_member_fk
                                   FOREIGN KEY (member_no) REFERENCES member(NO)
);
DROP SEQUENCE board_comment_seq;

CREATE SEQUENCE board_comment_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    nocache
    nocycle;
COMMIT;
SELECT * FROM board_comment;

INSERT INTO board_comment(
    NO,
    board_no,
    member_no,
    content
) VALUES (
             board_comment_seq.nextval,
             3,
             1,
             '댓글 테스트 내용입니다.'
         );
SELECT * FROM board_comment;
COMMIT;

CREATE TABLE board_like (
                            board_no	NUMBER CONSTRAINT board_like_board_nn NOT NULL,
                            member_no	NUMBER CONSTRAINT board_like_member_nn NOT NULL,
                            regdate		DATE   DEFAULT sysdate,

                            CONSTRAINT board_like_pk
                                PRIMARY KEY (board_no, member_no),

                            CONSTRAINT board_like_board_fk
                                FOREIGN KEY (board_no) REFERENCES board(NO)
                                    ON DELETE CASCADE,

                            CONSTRAINT board_like_member_fk
                                FOREIGN KEY (member_no) REFERENCES member(NO)
);

SELECT * FROM board_like;
COMMIT;

INSERT INTO board_like (
	board_no,
    member_no
) VALUES (
             3,
             1
         );

SELECT * FROM MEMBER;
SELECT * FROM board;
SELECT * FROM board_comment;
SELECT * FROM board_like;
COMMIT;