CREATE TABLE MEMBER (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(300),
    DETAIL_ADDRESS VARCHAR2(300),
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,
    
    CONSTRAINT CK_MEMBER_DELETED
        CHECK (IS_DELETED IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_PHONE
		CHECK (REGEXP_LIKE(PHONE,'^010-[0-9]{4}-[0-9]{4}$'))
);

CREATE TABLE MEMBER_WITHDRAW (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MEMBER_ID VARCHAR2(50),
    REASON VARCHAR2(500),
    REGDATE DATE DEFAULT SYSDATE
);

CREATE TABLE board (
                       NO			  NUMBER		CONSTRAINT board_no_pk PRIMARY KEY,
                       member_no	  NUMBER		CONSTRAINT board_member_nn NOT NULL,
                       board_type	  VARCHAR2(20)  CONSTRAINT board_type_nn NOT NULL,
                       restaurant_no NUMBER,
                       title		  VARCHAR2(300) CONSTRAINT board_title_nn NOT NULL,
                       content		  CLOB			CONSTRAINT board_content_nn NOT NULL,
                       rating		  NUMBER(2,1),
                       hit			  NUMBER		DEFAULT 0,
                       like_count	  NUMBER		DEFAULT 0,
                       category VARCHAR2(20),
                       taste_rating number(2,1),
                       facility_rating number(2,1),
                       service_rating number(2,1),
                       regdate		  DATE			DEFAULT sysdate,
                       update_date	  DATE,
                       IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,
						CONSTRAINT CK_BOARD_DELETED
    						CHECK (IS_DELETED IN ('Y', 'N')),
                       	CONSTRAINT board_member_fk
                           	FOREIGN KEY (member_no) REFERENCES member(NO),
                       	CONSTRAINT board_type_ck
                           	CHECK (board_type IN ('FREE', 'REVIEW')),
                       	CONSTRAINT board_rating_ck
                           	CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
                       	CONSTRAINT board_taste_ck
    						CHECK (taste_rating IS NULL OR taste_rating BETWEEN 1 AND 5),
					   	CONSTRAINT board_facility_ck
					    	CHECK (facility_rating IS NULL OR facility_rating BETWEEN 1 AND 5),
					   	CONSTRAINT board_service_ck
					    	CHECK (service_rating IS NULL OR service_rating BETWEEN 1 AND 5)
);

CREATE SEQUENCE board_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    nocache
    nocycle;

CREATE TABLE board_comment (
                               NO			NUMBER			CONSTRAINT board_comment_no_pk PRIMARY KEY,
                               board_no	NUMBER			CONSTRAINT board_comment_board_nn NOT NULL,
                               member_no	NUMBER			CONSTRAINT board_comment_member_nn NOT NULL,
                               content		VARCHAR2(2000)	CONSTRAINT board_comment_content_nn NOT NULL,
                               regdate		DATE 			DEFAULT sysdate,
                               update_date	DATE,
                               IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

								CONSTRAINT CK_BOARD_COMMENT_DELETED
    								CHECK (IS_DELETED IN ('Y', 'N')),

                               	CONSTRAINT board_comment_board_fk
                                   	FOREIGN KEY (board_no) REFERENCES board(NO)
                                       ON DELETE CASCADE ,

                               	CONSTRAINT board_comment_member_fk
                                   	FOREIGN KEY (member_no) REFERENCES member(NO)
);

CREATE SEQUENCE board_comment_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    nocache
    nocycle;

CREATE TABLE board_like (
                            board_no	NUMBER CONSTRAINT board_like_board_nn NOT NULL,
                            member_no	NUMBER CONSTRAINT board_like_member_nn NOT NULL,
                            regdate		DATE   DEFAULT sysdate,

                            CONSTRAINT board_like_pk
                                PRIMARY KEY (board_no, member_no),

                            CONSTRAINT board_like_board_fk
                                FOREIGN KEY (board_no) REFERENCES board(NO)
                                    ON DELETE CASCADE,

                            CONSTRAINT board_like_member_fk
                                FOREIGN KEY (member_no) REFERENCES member(NO)
);

--유저테이블
CREATE TABLE INQUIRY (

    NO NUMBER
        CONSTRAINT INQUIRY_NO_PK PRIMARY KEY,

    MEMBER_NO NUMBER
        CONSTRAINT INQUIRY_MEMBER_NN NOT NULL,

    TITLE VARCHAR2(300)
        CONSTRAINT INQUIRY_TITLE_NN NOT NULL,

    CONTENT CLOB
        CONSTRAINT INQUIRY_CONTENT_NN NOT NULL,

    PHONE VARCHAR2(20)
        CONSTRAINT INQUIRY_PHONE_NN NOT NULL,

    CATEGORY VARCHAR2(30)
        DEFAULT 'GENERAL'
        CONSTRAINT INQUIRY_CATEGORY_NN NOT NULL,

    STATUS VARCHAR2(20)
        DEFAULT 'WAITING'
        CONSTRAINT INQUIRY_STATUS_NN NOT NULL,

    IS_READ CHAR(1)
        DEFAULT 'N'
        CONSTRAINT INQUIRY_READ_NN NOT NULL,

    IS_DELETED CHAR(1)
        DEFAULT 'N'
        CONSTRAINT INQUIRY_DELETE_NN NOT NULL,

    REGDATE DATE
        DEFAULT SYSDATE,

    UPDATE_DATE DATE,

    CONSTRAINT INQUIRY_MEMBER_FK
        FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER(NO),

    CONSTRAINT INQUIRY_STATUS_CK
        CHECK (
            STATUS IN (
                'WAITING',
                'ANSWERED'
            )
        ),

    CONSTRAINT INQUIRY_READ_CK
        CHECK (
            IS_READ IN (
                'Y',
                'N'
            )
        ),

    CONSTRAINT INQUIRY_DELETE_CK
        CHECK (
            IS_DELETED IN (
                'Y',
                'N'
            )
        ),

    CONSTRAINT INQUIRY_CATEGORY_CK
        CHECK (
            CATEGORY IN (
                'GENERAL',
                'ACCOUNT',
                'BOARD',
                'RESTAURANT',
                'REPORT',
                'ETC'
            )
        ),
    CONSTRAINT CK_INQUIRY_PHONE
		CHECK (REGEXP_LIKE(PHONE,'^010-[0-9]{4}-[0-9]{4}$'))
);

CREATE SEQUENCE INQUIRY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999
NOCACHE
NOCYCLE;

--관리자 문의관리 테이블
CREATE TABLE INQUIRY_ANSWER (

    NO NUMBER
        CONSTRAINT INQUIRY_ANSWER_NO_PK PRIMARY KEY,

    INQUIRY_NO NUMBER
        CONSTRAINT INQUIRY_ANSWER_INQ_NN NOT NULL,

    ADMIN_NO NUMBER
        CONSTRAINT INQUIRY_ANSWER_ADMIN_NN NOT NULL,

    CONTENT CLOB
        CONSTRAINT INQUIRY_ANSWER_CONTENT_NN NOT NULL,

    IS_DELETED CHAR(1)
        DEFAULT 'N'
        CONSTRAINT INQUIRY_ANSWER_DELETE_NN NOT NULL,

    REGDATE DATE
        DEFAULT SYSDATE,

    UPDATE_DATE DATE,

    CONSTRAINT INQUIRY_ANSWER_INQ_FK
        FOREIGN KEY (INQUIRY_NO)
        REFERENCES INQUIRY(NO)
        ON DELETE CASCADE,

    CONSTRAINT INQUIRY_ANSWER_ADMIN_FK
        FOREIGN KEY (ADMIN_NO)
        REFERENCES MEMBER(NO),

    CONSTRAINT INQUIRY_ANSWER_DELETE_CK
        CHECK (
            IS_DELETED IN (
                'Y',
                'N'
            )
        ),
    CONSTRAINT UK_INQUIRY_ANSWER
		UNIQUE(INQUIRY_NO)

);

CREATE SEQUENCE INQUIRY_ANSWER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999
NOCACHE
NOCYCLE;


