--맴버--
CREATE TABLE MEMBER (
                        NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        MEMBER_ID VARCHAR2(50) UNIQUE NOT NULL,
                        PASSWORD VARCHAR2(100) NOT NULL,
                        NAME VARCHAR2(30) NOT NULL,
                        GENDER CHAR(1) NOT NULL,
                        BIRTH_DATE DATE NOT NULL,
                        PHONE VARCHAR2(20) NOT NULL,
                        ADDRESS VARCHAR2(300),
                        ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
                        REGDATE DATE DEFAULT SYSDATE
);


--식당--
CREATE TABLE restaurant (
                            no NUMBER CONSTRAINT restaurant_no_pk PRIMARY KEY,
                            name VARCHAR2(100) CONSTRAINT restaurant_name_nn NOT NULL,
                            region VARCHAR2(50),
                            category VARCHAR2(50),
                            address VARCHAR2(300),
                            phone VARCHAR2(20),
                            description VARCHAR2(1000)
);


CREATE SEQUENCE restaurant_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;




--board--
CREATE TABLE board (
                       no NUMBER CONSTRAINT board_no_pk PRIMARY KEY,
                       member_no NUMBER CONSTRAINT board_member_nn NOT NULL,
                       board_type VARCHAR2(20) CONSTRAINT board_type_nn NOT NULL,
                       restaurant_no NUMBER,
                       title VARCHAR2(300) CONSTRAINT board_title_nn NOT NULL,
                       content CLOB CONSTRAINT board_content_nn NOT NULL,
                       rating NUMBER(2,1),
                       hit NUMBER DEFAULT 0,
                       like_count NUMBER DEFAULT 0,
                       regdate DATE DEFAULT sysdate,
                       update_date DATE,

                       CONSTRAINT board_member_fk
                           FOREIGN KEY (member_no) REFERENCES member(no),

                       CONSTRAINT board_restaurant_fk
                           FOREIGN KEY (restaurant_no) REFERENCES restaurant(no),

                       CONSTRAINT board_type_ck
                           CHECK (board_type IN ('FREE', 'REVIEW')),

                       CONSTRAINT board_rating_ck
                           CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);


CREATE SEQUENCE board_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999
    NOCACHE
NOCYCLE;


--이미지--
CREATE TABLE board_image (
                             no NUMBER CONSTRAINT board_image_no_pk PRIMARY KEY,
                             board_no NUMBER CONSTRAINT board_image_board_nn NOT NULL,
                             image_url VARCHAR2(300) CONSTRAINT board_image_url_nn NOT NULL,

                             CONSTRAINT board_image_board_fk
                                 FOREIGN KEY (board_no) REFERENCES board(no)
);


CREATE SEQUENCE board_image_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;




--댓글--
CREATE TABLE board_comment (
                               no NUMBER CONSTRAINT board_comment_no_pk PRIMARY KEY,
                               board_no NUMBER CONSTRAINT board_comment_board_nn NOT NULL,
                               member_no NUMBER CONSTRAINT board_comment_member_nn NOT NULL,
                               content VARCHAR2(1000) CONSTRAINT board_comment_content_nn NOT NULL,
                               regdate DATE DEFAULT SYSDATE,

                               CONSTRAINT board_comment_board_fk
                                   FOREIGN KEY (board_no) REFERENCES board(no),

                               CONSTRAINT board_comment_member_fk
                                   FOREIGN KEY (member_no) REFERENCES member(no)
);

CREATE SEQUENCE board_comment_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;




CREATE TABLE board_like (
                            no NUMBER PRIMARY KEY,
                            board_no NUMBER NOT NULL,
                            member_no NUMBER NOT NULL,

                            CONSTRAINT board_like_board_fk
                                FOREIGN KEY(board_no) REFERENCES board(no),

                            CONSTRAINT board_like_member_fk
                                FOREIGN KEY(member_no) REFERENCES member(no),

                            CONSTRAINT board_like_unique
                                UNIQUE(board_no, member_no)
);


CREATE SEQUENCE board_like_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;